title: "{% nyu wh templater %}"
description: ''
baseurl: '/wh-reply' 
url: ''
logo: '/assets/logo.svg'

remote_theme: daviddarnes/garth
plugins:
  - jekyll-feed
  - jekyll-remote-theme
sass:
  quiet_deps: true